export enum AppEvent {
  CHANGE_HEAT = 'CHANGE_HEAT',
  EDIT_WIDGET = 'EDIT_WIDGET',
  DELETE_WIDGET = 'DELETE_WIDGET',
  ADD_WIDGET = 'ADD_WIDGET',
  LAYOUT_CHANGED = 'LAYOUT_CHANGED',
  NOTIFICATION = 'NOTIFICATION',
  SHOW_NOTIFICATION = 'SHOW_NOTIFICATION',
  LOGOUT = 'LOGOUT',
  FORBIDDEN = 'FORBIDDEN',
  UPDATE_ORGANIZATION_SWITCH = 'UPDATE_ORGANIZATION_SWITCH',
  SET_LINK_POPUP = 'SET_LINK_POPUP',
}
